name: ${project.artifactId}
version: ${project.version}

main: de.webrush.WeBrush
api-version: 1.13

depend: [WorldEdit]

commands:
   webrush:
      permission: webrush.admin
      description: Loads an brush.
      usage: /webrush