name: WeBrush
main: de.webrush.WeBrush
version: 1.0.5
api-version: 1.13
depend: [WorldEdit]
commands:
   webrush:
      permission: webrush.admin
      description: Loads an brush.
      usage: /webrush